/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FullCalendarTest: typeof import('./../src/components/FullCalendarTest/index.vue')['default']
    Naive: typeof import('./../src/components/Naive/index.vue')['default']
    Navigation: typeof import('./../src/components/Navigation/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMention: typeof import('naive-ui')['NMention']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSplit: typeof import('naive-ui')['NSplit']
    NTable: typeof import('naive-ui')['NTable']
    NUpload: typeof import('naive-ui')['NUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableDesign: typeof import('./../src/components/TableDesign/index.vue')['default']
    ViconsIonicons5: typeof import('./../src/components/ViconsIonicons5/index.vue')['default']
    WebSocket: typeof import('./../src/components/WebSocket/index.vue')['default']
  }
}
